// src/feed/candidateMeals.ts
import type { CandidateMeal } from "./types";

export const candidateMeals: CandidateMeal[] = [
  {
    id: "m01",
    merchant: "Zen Kitchen",
    item: "Chicken Teriyaki Bowl",
    cuisine: "Asian",
    price: 14.80,
    pickupEta: 11,
    deliveryEta: 25,
    rating: 4.7,
    distanceKm: 0.4,
    tags: ["Chicken", "Asian", "Light meals", "Rice"],
  },
  {
    id: "m02",
    merchant: "Green Leaf Cafe",
    item: "Grilled Chicken Salad",
    cuisine: "American",
    price: 13.50,
    pickupEta: 8,
    deliveryEta: 20,
    rating: 4.5,
    distanceKm: 0.6,
    tags: ["Chicken", "Light meals", "Salad", "Healthy"],
  },
  {
    id: "m03",
    merchant: "Pho 888",
    item: "Chicken Pho",
    cuisine: "Vietnamese",
    price: 15.00,
    pickupEta: 12,
    deliveryEta: 28,
    rating: 4.8,
    distanceKm: 0.8,
    tags: ["Asian", "Chicken", "Soup", "Light meals"],
  },
  {
    id: "m04",
    merchant: "Burrito Box",
    item: "Chicken Burrito",
    cuisine: "Mexican",
    price: 12.00,
    pickupEta: 7,
    deliveryEta: 18,
    rating: 4.3,
    distanceKm: 0.3,
    tags: ["Chicken", "Mexican", "Quick"],
  },
  {
    id: "m05",
    merchant: "Sushi Spot",
    item: "Salmon Sashimi Set",
    cuisine: "Japanese",
    price: 18.00,
    pickupEta: 10,
    deliveryEta: 22,
    rating: 4.9,
    distanceKm: 1.1,
    tags: ["Asian", "Sushi", "Light meals", "Fish"],
  },
  {
    id: "m06",
    merchant: "Noodle House",
    item: "Dan Dan Noodles",
    cuisine: "Chinese",
    price: 11.50,
    pickupEta: 9,
    deliveryEta: 21,
    rating: 4.4,
    distanceKm: 0.5,
    tags: ["Asian", "Noodles", "Spicy"],
  },
  {
    id: "m07",
    merchant: "The Sandwich Co.",
    item: "Turkey Club Sandwich",
    cuisine: "American",
    price: 10.00,
    pickupEta: 5,
    deliveryEta: 15,
    rating: 4.2,
    distanceKm: 0.2,
    tags: ["Quick", "Light meals", "Sandwich"],
  },
  {
    id: "m08",
    merchant: "Poke Bowl Bar",
    item: "Tuna Poke Bowl",
    cuisine: "Hawaiian",
    price: 16.00,
    pickupEta: 8,
    deliveryEta: 20,
    rating: 4.6,
    distanceKm: 0.7,
    tags: ["Light meals", "Fish", "Healthy", "Asian"],
  },
  {
    id: "m09",
    merchant: "Curry Corner",
    item: "Chicken Tikka Masala",
    cuisine: "Indian",
    price: 14.00,
    pickupEta: 15,
    deliveryEta: 30,
    rating: 4.7,
    distanceKm: 1.0,
    tags: ["Asian", "Chicken", "Spicy"],
  },
  {
    id: "m10",
    merchant: "Steam Bun House",
    item: "BBQ Pork Bao x3",
    cuisine: "Chinese",
    price: 9.00,
    pickupEta: 6,
    deliveryEta: 18,
    rating: 4.5,
    distanceKm: 0.4,
    tags: ["Asian", "Light meals", "Quick"],
  },
  {
    id: "m11",
    merchant: "Ramen Lab",
    item: "Shoyu Ramen",
    cuisine: "Japanese",
    price: 16.50,
    pickupEta: 13,
    deliveryEta: 27,
    rating: 4.8,
    distanceKm: 0.9,
    tags: ["Asian", "Noodles", "Soup"],
  },
  {
    id: "m12",
    merchant: "Deli Fresh",
    item: "Caesar Wrap",
    cuisine: "American",
    price: 11.00,
    pickupEta: 5,
    deliveryEta: 14,
    rating: 4.1,
    distanceKm: 0.3,
    tags: ["Quick", "Light meals", "Healthy"],
  },
  {
    id: "m13",
    merchant: "Thai Palace",
    item: "Pad Thai (Chicken)",
    cuisine: "Thai",
    price: 13.00,
    pickupEta: 14,
    deliveryEta: 26,
    rating: 4.6,
    distanceKm: 0.8,
    tags: ["Asian", "Chicken", "Noodles"],
  },
  {
    id: "m14",
    merchant: "Acai Bowl Co.",
    item: "Dragon Fruit Acai Bowl",
    cuisine: "Healthy",
    price: 12.50,
    pickupEta: 6,
    deliveryEta: 16,
    rating: 4.4,
    distanceKm: 0.5,
    tags: ["Light meals", "Healthy", "Breakfast", "Snack"],
  },
  {
    id: "m15",
    merchant: "Dim Sum Express",
    item: "Har Gow + Siu Mai Set",
    cuisine: "Chinese",
    price: 13.00,
    pickupEta: 10,
    deliveryEta: 22,
    rating: 4.5,
    distanceKm: 0.6,
    tags: ["Asian", "Light meals"],
  },
  {
    id: "m16",
    merchant: "Burger Joint",
    item: "Classic Cheeseburger",
    cuisine: "American",
    price: 11.50,
    pickupEta: 8,
    deliveryEta: 18,
    rating: 4.3,
    distanceKm: 0.4,
    tags: ["Quick", "Beef"],
  },
  {
    id: "m17",
    merchant: "Soba Noodle Bar",
    item: "Cold Soba with Dipping Sauce",
    cuisine: "Japanese",
    price: 12.00,
    pickupEta: 9,
    deliveryEta: 20,
    rating: 4.5,
    distanceKm: 0.7,
    tags: ["Asian", "Light meals", "Noodles"],
  },
  {
    id: "m18",
    merchant: "Shawarma King",
    item: "Chicken Shawarma Plate",
    cuisine: "Middle Eastern",
    price: 13.50,
    pickupEta: 7,
    deliveryEta: 19,
    rating: 4.4,
    distanceKm: 0.5,
    tags: ["Chicken", "Quick"],
  },
  {
    id: "m19",
    merchant: "Pita Palace",
    item: "Falafel Wrap",
    cuisine: "Mediterranean",
    price: 10.50,
    pickupEta: 6,
    deliveryEta: 16,
    rating: 4.3,
    distanceKm: 0.4,
    tags: ["Light meals", "Vegetarian", "Quick"],
  },
  {
    id: "m20",
    merchant: "Premium Sushi Bar",
    item: "Omakase Bento Box",
    cuisine: "Japanese",
    price: 28.00,
    pickupEta: 20,
    deliveryEta: 35,
    rating: 5.0,
    distanceKm: 1.5,
    tags: ["Asian", "Sushi", "Premium"],
  },
];
